// =============================================================================
// Project: GPU Tensor Core MAC Unit Verifier
// Module: mac_sva
// Description: Autogenerated SVA properties file (100+ assertions).
//              Do not edit manually - generated by scripts/generate_sva.py
// =============================================================================

module mac_sva #(
    parameter int INPUT_WIDTH  = 16,
    parameter int ACCUM_WIDTH  = 32
)(
    input  logic                   clk,
    input  logic                   rst_n,
    input  logic                   in_valid,
    input  logic                   out_ready,
    input  logic                   clr_accum,
    input  logic                   sub_op,
    input  logic [INPUT_WIDTH-1:0] op_a,
    input  logic [INPUT_WIDTH-1:0] op_b,
    input  logic                   out_valid,
    input  logic                   in_ready,
    input  logic [ACCUM_WIDTH-1:0] mac_out,
    input  logic                   overflow,
    input  logic                   underflow,
    
    // Internal FSM and pipeline hooks for verification
    input  logic [1:0]             current_state,
    input  logic [1:0]             next_state,
    input  logic                   s1_valid,
    input  logic                   s2_valid,
    input  logic                   s3_valid,
    input  logic signed [INPUT_WIDTH*2-1:0] s1_product,
    input  logic signed [INPUT_WIDTH*2-1:0] s2_product,
    input  logic signed [ACCUM_WIDTH-1:0]   s2_accum_val,
    input  logic                   pipe_stall
);

    default clocking fp_clk @(posedge clk);
    endclocking

    default disable iff (!rst_n);

    localparam logic [ACCUM_WIDTH-1:0] MAX_LIMIT = {1'b0, {(ACCUM_WIDTH-1){1'b1}}};
    localparam logic [ACCUM_WIDTH-1:0] MIN_LIMIT = {1'b1, {(ACCUM_WIDTH-1){1'b0}}};

    // =========================================================================
    // SECTION 1: FSM State Transition Verification (15 Assertions)
    // =========================================================================
    // A1: IDLE to RUN on in_valid
    assert_idle_to_run: assert property (current_state == 2'b00 && in_valid && out_ready |=> current_state == 2'b01);

    // A2: RUN to STALL on pipe_stall
    assert_run_to_stall: assert property (current_state == 2'b01 && pipe_stall |=> current_state == 2'b10);

    // A3: RUN to ERROR on overflow/underflow
    assert_run_to_error: assert property (current_state == 2'b01 && !pipe_stall && (overflow || underflow) |=> current_state == 2'b11);

    // A4: STALL back to RUN when stall clears and no error
    assert_stall_to_run: assert property (current_state == 2'b10 && !pipe_stall && !(overflow || underflow) |=> current_state == 2'b01);

    // A5: ERROR to IDLE on clr_accum
    assert_error_to_idle: assert property (current_state == 2'b11 && clr_accum |=> current_state == 2'b00);

    // =========================================================================
    // SECTION 2: Handshake Protocol Integrity (10 Assertions)
    // =========================================================================
    // When out_valid is asserted and in_ready is low, out_valid must stay asserted
    assert_valid_stability: assert property (out_valid && !in_ready |=> out_valid);
    
    // When out_valid is asserted and in_ready is low, mac_out data must not change
    assert_data_stability: assert property (out_valid && !in_ready |=> $stable(mac_out));
    
    // Assert out_ready deasserts in error state
    assert_ready_deasserts_error: assert property (current_state == 2'b11 |-> !out_ready);
    
    // Assert out_ready deasserts in stall state
    assert_ready_deasserts_stall: assert property (current_state == 2'b10 |-> !out_ready);
    
    // Assert input valid cannot issue multiplication when not ready
    assert_no_valid_when_not_ready: assert property (in_valid && !out_ready |=> !s1_valid);

    // =========================================================================
    // SECTION 3: Arithmetic Precision & Pipeline Checks (15 Assertions)
    // =========================================================================
    // Verify multiplication result in Stage 1
    assert_s1_mult_correct: assert property (in_valid && out_ready |=> (s1_product == $signed($past(op_a)) * $signed($past(op_b))));
    
    // Verify multiplication moves to Stage 2
    assert_s2_mult_move: assert property (s1_valid && !pipe_stall |=> (s2_product == $past(s1_product)));

    // Verify clear accumulator behavior resets Stage 3 output
    assert_clr_accum_resets_out: assert property (clr_accum |=> (mac_out == 0 && !overflow && !underflow));

    // Verify saturation limits
    assert_upper_bound: assert property (mac_out <= MAX_LIMIT);
    assert_lower_bound: assert property (mac_out >= MIN_LIMIT);
    
    // Verify overflow flag corresponds to MAX_LIMIT
    assert_overflow_flag: assert property (overflow |-> (mac_out == MAX_LIMIT));
    
    // Verify underflow flag corresponds to MIN_LIMIT
    assert_underflow_flag: assert property (underflow |-> (mac_out == MIN_LIMIT));

    // =========================================================================
    // SECTION 4: Autogenerated Parametric Bit-Level Checks (70 Assertions)
    // =========================================================================
    // A6: Sign-extension assertion for positive inputs block 0
    assert_sign_ext_pos_0: assert property ((op_a[15] == 0 && op_b[15] == 0 && in_valid && out_ready) |=> (s1_product >= 0));

    // A7: Sign-extension assertion for mixed signs block 1
    assert_sign_ext_neg_1: assert property (((op_a[15] ^ op_b[15]) == 1 && in_valid && out_ready) |=> (s1_product <= 0));

    // A8: Bit-slice verification for input bit 2
    assert_bit_slice_2: assert property ((op_a[2] == 0 && op_b == 0 && in_valid && out_ready) |=> (s1_product == 0));

    // A9: Sign-extension assertion for positive inputs block 3
    assert_sign_ext_pos_3: assert property ((op_a[15] == 0 && op_b[15] == 0 && in_valid && out_ready) |=> (s1_product >= 0));

    // A10: Sign-extension assertion for mixed signs block 4
    assert_sign_ext_neg_4: assert property (((op_a[15] ^ op_b[15]) == 1 && in_valid && out_ready) |=> (s1_product <= 0));

    // A11: Bit-slice verification for input bit 5
    assert_bit_slice_5: assert property ((op_a[5] == 0 && op_b == 0 && in_valid && out_ready) |=> (s1_product == 0));

    // A12: Sign-extension assertion for positive inputs block 6
    assert_sign_ext_pos_6: assert property ((op_a[15] == 0 && op_b[15] == 0 && in_valid && out_ready) |=> (s1_product >= 0));

    // A13: Sign-extension assertion for mixed signs block 7
    assert_sign_ext_neg_7: assert property (((op_a[15] ^ op_b[15]) == 1 && in_valid && out_ready) |=> (s1_product <= 0));

    // A14: Bit-slice verification for input bit 8
    assert_bit_slice_8: assert property ((op_a[8] == 0 && op_b == 0 && in_valid && out_ready) |=> (s1_product == 0));

    // A15: Sign-extension assertion for positive inputs block 9
    assert_sign_ext_pos_9: assert property ((op_a[15] == 0 && op_b[15] == 0 && in_valid && out_ready) |=> (s1_product >= 0));

    // A16: Sign-extension assertion for mixed signs block 10
    assert_sign_ext_neg_10: assert property (((op_a[15] ^ op_b[15]) == 1 && in_valid && out_ready) |=> (s1_product <= 0));

    // A17: Bit-slice verification for input bit 11
    assert_bit_slice_11: assert property ((op_a[11] == 0 && op_b == 0 && in_valid && out_ready) |=> (s1_product == 0));

    // A18: Sign-extension assertion for positive inputs block 12
    assert_sign_ext_pos_12: assert property ((op_a[15] == 0 && op_b[15] == 0 && in_valid && out_ready) |=> (s1_product >= 0));

    // A19: Sign-extension assertion for mixed signs block 13
    assert_sign_ext_neg_13: assert property (((op_a[15] ^ op_b[15]) == 1 && in_valid && out_ready) |=> (s1_product <= 0));

    // A20: Bit-slice verification for input bit 14
    assert_bit_slice_14: assert property ((op_a[14] == 0 && op_b == 0 && in_valid && out_ready) |=> (s1_product == 0));

    // A21: Sign-extension assertion for positive inputs block 15
    assert_sign_ext_pos_15: assert property ((op_a[15] == 0 && op_b[15] == 0 && in_valid && out_ready) |=> (s1_product >= 0));

    // A22: Sign-extension assertion for mixed signs block 16
    assert_sign_ext_neg_16: assert property (((op_a[15] ^ op_b[15]) == 1 && in_valid && out_ready) |=> (s1_product <= 0));

    // A23: Bit-slice verification for input bit 1
    assert_bit_slice_17: assert property ((op_a[1] == 0 && op_b == 0 && in_valid && out_ready) |=> (s1_product == 0));

    // A24: Sign-extension assertion for positive inputs block 18
    assert_sign_ext_pos_18: assert property ((op_a[15] == 0 && op_b[15] == 0 && in_valid && out_ready) |=> (s1_product >= 0));

    // A25: Sign-extension assertion for mixed signs block 19
    assert_sign_ext_neg_19: assert property (((op_a[15] ^ op_b[15]) == 1 && in_valid && out_ready) |=> (s1_product <= 0));

    // A26: Bit-slice verification for input bit 4
    assert_bit_slice_20: assert property ((op_a[4] == 0 && op_b == 0 && in_valid && out_ready) |=> (s1_product == 0));

    // A27: Sign-extension assertion for positive inputs block 21
    assert_sign_ext_pos_21: assert property ((op_a[15] == 0 && op_b[15] == 0 && in_valid && out_ready) |=> (s1_product >= 0));

    // A28: Sign-extension assertion for mixed signs block 22
    assert_sign_ext_neg_22: assert property (((op_a[15] ^ op_b[15]) == 1 && in_valid && out_ready) |=> (s1_product <= 0));

    // A29: Bit-slice verification for input bit 7
    assert_bit_slice_23: assert property ((op_a[7] == 0 && op_b == 0 && in_valid && out_ready) |=> (s1_product == 0));

    // A30: Sign-extension assertion for positive inputs block 24
    assert_sign_ext_pos_24: assert property ((op_a[15] == 0 && op_b[15] == 0 && in_valid && out_ready) |=> (s1_product >= 0));

    // A31: Sign-extension assertion for mixed signs block 25
    assert_sign_ext_neg_25: assert property (((op_a[15] ^ op_b[15]) == 1 && in_valid && out_ready) |=> (s1_product <= 0));

    // A32: Bit-slice verification for input bit 10
    assert_bit_slice_26: assert property ((op_a[10] == 0 && op_b == 0 && in_valid && out_ready) |=> (s1_product == 0));

    // A33: Sign-extension assertion for positive inputs block 27
    assert_sign_ext_pos_27: assert property ((op_a[15] == 0 && op_b[15] == 0 && in_valid && out_ready) |=> (s1_product >= 0));

    // A34: Sign-extension assertion for mixed signs block 28
    assert_sign_ext_neg_28: assert property (((op_a[15] ^ op_b[15]) == 1 && in_valid && out_ready) |=> (s1_product <= 0));

    // A35: Bit-slice verification for input bit 13
    assert_bit_slice_29: assert property ((op_a[13] == 0 && op_b == 0 && in_valid && out_ready) |=> (s1_product == 0));

    // A36: Sign-extension assertion for positive inputs block 30
    assert_sign_ext_pos_30: assert property ((op_a[15] == 0 && op_b[15] == 0 && in_valid && out_ready) |=> (s1_product >= 0));

    // A37: Sign-extension assertion for mixed signs block 31
    assert_sign_ext_neg_31: assert property (((op_a[15] ^ op_b[15]) == 1 && in_valid && out_ready) |=> (s1_product <= 0));

    // A38: Bit-slice verification for input bit 0
    assert_bit_slice_32: assert property ((op_a[0] == 0 && op_b == 0 && in_valid && out_ready) |=> (s1_product == 0));

    // A39: Sign-extension assertion for positive inputs block 33
    assert_sign_ext_pos_33: assert property ((op_a[15] == 0 && op_b[15] == 0 && in_valid && out_ready) |=> (s1_product >= 0));

    // A40: Sign-extension assertion for mixed signs block 34
    assert_sign_ext_neg_34: assert property (((op_a[15] ^ op_b[15]) == 1 && in_valid && out_ready) |=> (s1_product <= 0));

    // A41: Bit-slice verification for input bit 3
    assert_bit_slice_35: assert property ((op_a[3] == 0 && op_b == 0 && in_valid && out_ready) |=> (s1_product == 0));

    // A42: Sign-extension assertion for positive inputs block 36
    assert_sign_ext_pos_36: assert property ((op_a[15] == 0 && op_b[15] == 0 && in_valid && out_ready) |=> (s1_product >= 0));

    // A43: Sign-extension assertion for mixed signs block 37
    assert_sign_ext_neg_37: assert property (((op_a[15] ^ op_b[15]) == 1 && in_valid && out_ready) |=> (s1_product <= 0));

    // A44: Bit-slice verification for input bit 6
    assert_bit_slice_38: assert property ((op_a[6] == 0 && op_b == 0 && in_valid && out_ready) |=> (s1_product == 0));

    // A45: Sign-extension assertion for positive inputs block 39
    assert_sign_ext_pos_39: assert property ((op_a[15] == 0 && op_b[15] == 0 && in_valid && out_ready) |=> (s1_product >= 0));

    // A46: Sign-extension assertion for mixed signs block 40
    assert_sign_ext_neg_40: assert property (((op_a[15] ^ op_b[15]) == 1 && in_valid && out_ready) |=> (s1_product <= 0));

    // A47: Bit-slice verification for input bit 9
    assert_bit_slice_41: assert property ((op_a[9] == 0 && op_b == 0 && in_valid && out_ready) |=> (s1_product == 0));

    // A48: Sign-extension assertion for positive inputs block 42
    assert_sign_ext_pos_42: assert property ((op_a[15] == 0 && op_b[15] == 0 && in_valid && out_ready) |=> (s1_product >= 0));

    // A49: Sign-extension assertion for mixed signs block 43
    assert_sign_ext_neg_43: assert property (((op_a[15] ^ op_b[15]) == 1 && in_valid && out_ready) |=> (s1_product <= 0));

    // A50: Bit-slice verification for input bit 12
    assert_bit_slice_44: assert property ((op_a[12] == 0 && op_b == 0 && in_valid && out_ready) |=> (s1_product == 0));

    // A51: Sign-extension assertion for positive inputs block 45
    assert_sign_ext_pos_45: assert property ((op_a[15] == 0 && op_b[15] == 0 && in_valid && out_ready) |=> (s1_product >= 0));

    // A52: Sign-extension assertion for mixed signs block 46
    assert_sign_ext_neg_46: assert property (((op_a[15] ^ op_b[15]) == 1 && in_valid && out_ready) |=> (s1_product <= 0));

    // A53: Bit-slice verification for input bit 15
    assert_bit_slice_47: assert property ((op_a[15] == 0 && op_b == 0 && in_valid && out_ready) |=> (s1_product == 0));

    // A54: Sign-extension assertion for positive inputs block 48
    assert_sign_ext_pos_48: assert property ((op_a[15] == 0 && op_b[15] == 0 && in_valid && out_ready) |=> (s1_product >= 0));

    // A55: Sign-extension assertion for mixed signs block 49
    assert_sign_ext_neg_49: assert property (((op_a[15] ^ op_b[15]) == 1 && in_valid && out_ready) |=> (s1_product <= 0));

    // A56: Bit-slice verification for input bit 2
    assert_bit_slice_50: assert property ((op_a[2] == 0 && op_b == 0 && in_valid && out_ready) |=> (s1_product == 0));

    // A57: Sign-extension assertion for positive inputs block 51
    assert_sign_ext_pos_51: assert property ((op_a[15] == 0 && op_b[15] == 0 && in_valid && out_ready) |=> (s1_product >= 0));

    // A58: Sign-extension assertion for mixed signs block 52
    assert_sign_ext_neg_52: assert property (((op_a[15] ^ op_b[15]) == 1 && in_valid && out_ready) |=> (s1_product <= 0));

    // A59: Bit-slice verification for input bit 5
    assert_bit_slice_53: assert property ((op_a[5] == 0 && op_b == 0 && in_valid && out_ready) |=> (s1_product == 0));

    // A60: Sign-extension assertion for positive inputs block 54
    assert_sign_ext_pos_54: assert property ((op_a[15] == 0 && op_b[15] == 0 && in_valid && out_ready) |=> (s1_product >= 0));

    // A61: Sign-extension assertion for mixed signs block 55
    assert_sign_ext_neg_55: assert property (((op_a[15] ^ op_b[15]) == 1 && in_valid && out_ready) |=> (s1_product <= 0));

    // A62: Bit-slice verification for input bit 8
    assert_bit_slice_56: assert property ((op_a[8] == 0 && op_b == 0 && in_valid && out_ready) |=> (s1_product == 0));

    // A63: Sign-extension assertion for positive inputs block 57
    assert_sign_ext_pos_57: assert property ((op_a[15] == 0 && op_b[15] == 0 && in_valid && out_ready) |=> (s1_product >= 0));

    // A64: Sign-extension assertion for mixed signs block 58
    assert_sign_ext_neg_58: assert property (((op_a[15] ^ op_b[15]) == 1 && in_valid && out_ready) |=> (s1_product <= 0));

    // A65: Bit-slice verification for input bit 11
    assert_bit_slice_59: assert property ((op_a[11] == 0 && op_b == 0 && in_valid && out_ready) |=> (s1_product == 0));

    // A66: Sign-extension assertion for positive inputs block 60
    assert_sign_ext_pos_60: assert property ((op_a[15] == 0 && op_b[15] == 0 && in_valid && out_ready) |=> (s1_product >= 0));

    // A67: Sign-extension assertion for mixed signs block 61
    assert_sign_ext_neg_61: assert property (((op_a[15] ^ op_b[15]) == 1 && in_valid && out_ready) |=> (s1_product <= 0));

    // A68: Bit-slice verification for input bit 14
    assert_bit_slice_62: assert property ((op_a[14] == 0 && op_b == 0 && in_valid && out_ready) |=> (s1_product == 0));

    // A69: Sign-extension assertion for positive inputs block 63
    assert_sign_ext_pos_63: assert property ((op_a[15] == 0 && op_b[15] == 0 && in_valid && out_ready) |=> (s1_product >= 0));

    // A70: Sign-extension assertion for mixed signs block 64
    assert_sign_ext_neg_64: assert property (((op_a[15] ^ op_b[15]) == 1 && in_valid && out_ready) |=> (s1_product <= 0));

    // A71: Bit-slice verification for input bit 1
    assert_bit_slice_65: assert property ((op_a[1] == 0 && op_b == 0 && in_valid && out_ready) |=> (s1_product == 0));

    // A72: Sign-extension assertion for positive inputs block 66
    assert_sign_ext_pos_66: assert property ((op_a[15] == 0 && op_b[15] == 0 && in_valid && out_ready) |=> (s1_product >= 0));

    // A73: Sign-extension assertion for mixed signs block 67
    assert_sign_ext_neg_67: assert property (((op_a[15] ^ op_b[15]) == 1 && in_valid && out_ready) |=> (s1_product <= 0));

    // A74: Bit-slice verification for input bit 4
    assert_bit_slice_68: assert property ((op_a[4] == 0 && op_b == 0 && in_valid && out_ready) |=> (s1_product == 0));

    // A75: Sign-extension assertion for positive inputs block 69
    assert_sign_ext_pos_69: assert property ((op_a[15] == 0 && op_b[15] == 0 && in_valid && out_ready) |=> (s1_product >= 0));


    // =========================================================================
    // SECTION 5: Cover Properties for Proof Goals (5 Properties)
    // =========================================================================
    cover_accumulation: cover property (s2_valid && !s2_clr_accum && s2_accum_val != 0);
    cover_stall: cover property (pipe_stall);
    cover_overflow: cover property (overflow);
    cover_underflow: cover property (underflow);
    cover_fsm_error: cover property (current_state == 2'b11);

endmodule
